# Basic info.
site_name: makedeb Docs
repo_name: makedeb/makedeb
repo_url: https://github.com/makedeb/makedeb/
edit_uri: https://github.com/makedeb/makedeb-docs/blob/master/docs/

# Extra CSS sheets.
extra_css:
  - stylesheets/extra.css

# Plugins.
plugins:
  - search
  - macros

# Extensions.
markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - extras/.icons

# Copyright.
copyright: Copyright &copy; 2021 Hunter Wittenborn. See the source for copying conditions.

# Extras.
extra:
  env:
    proget_url: "proget.hunterwittenborn.com"
    mpr_url: "mpr.hunterwittenborn.com"
    aur_url: "aur.archlinux.org"
    github_url: "github.com"
    site_url: "docs.hunterwittenborn.com"

  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/makedeb/"

    - icon: matrix
      link: "https://matrix.to/#/#makedeb:hunterwittenborn.com"

# Navigation menu.
nav:
  - Home:
    - Introduction: home/introduction.md
    - Installing:
      - Release types: home/installing/release-types.md
      - APT repository: home/installing/apt-repository.md
      - makedeb Package Repository: home/installing/makedeb-package-repository.md
      - Arch User Repository: home/installing/arch-user-repository.md
      - Docker: home/installing/docker.md

  - makedeb:
    - Creating packages: makedeb/creating-packages.md
    - PKGBUILD specification:
      - Variables: makedeb/pkgbuild-specification/variables.md
      - Functions: makedeb/pkgbuild-specification/functions.md

  - MPR:
    - Introduction: mpr/introduction.md
    - Getting started: mpr/getting-started.md
    - List of MPR helpers: mpr/list-of-mpr-helpers.md
    - Using the MPR:
      - Installing packages: mpr/using-the-mpr/installing-packages.md
      - Uploading PKGBUILDs: mpr/using-the-mpr/uploading-pkgbuilds.md
      - Using the RPC interface: mpr/using-the-mpr/using-the-rpc-interface.md
    - MPR user guidelines:
      - Marking maintainers in a PKGBUILD: mpr/mpr-user-guidelines/marking-maintainers-in-a-pkgbuild.md
      - Package relationships: mpr/mpr-user-guidelines/package-relationships.md
      - Using testing features: mpr/mpr-user-guidelines/using-testing-features.md

  - Support:
    - Getting support: support/getting-support.md
    - Reporting issues: support/reporting-issues.md

# Theme info.
theme:
  name: material
  logo: assets/logo.png
  custom_dir: docs/extras
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
